In [2]:
import torch
import numpy as np
import torch.nn as nn


In [17]:
def get_jacobian(net, x, noutputs):
    x = x.squeeze()
    n = x.size()[0]
    x = x.repeat(noutputs, 1)
    x.requires_grad_(True)
    y = net(x)
    y.backward(torch.eye(noutputs), create_graph=True)
    
    return x.grad

In [18]:
class Net(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(Net, self).__init__()

        self.layer1 = nn.Linear(input_size, hidden_size, bias=False)
        nn.init.xavier_uniform(self.layer1.weight.data)

    def forward(self, input):
        x = self.layer1(input)
        return self.layer1(x)
    
    

    

In [19]:
net = Net(3, 3)

/Users/michelle/miniconda3/envs/guapo/lib/python3.6/site-packages/ipykernel_launcher.py:6: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  


In [25]:
x = np.array((1, 1, 1))
x = torch.from_numpy(x).float()

print(net.layer1.weight.data@net.layer1.weight.data)

tensor([[-0.0947,  0.1192,  0.3029],
        [-0.7268,  0.0206, -0.6454],
        [ 1.3653, -0.3959,  1.2509]])


In [26]:
net(x)

tensor([ 0.3273, -1.3516,  2.2202], grad_fn=<SqueezeBackward3>)

In [27]:
jacobian = get_jacobian(net, x, 3)
print(jacobian)

tensor([[-0.0947,  0.1192,  0.3029],
        [-0.7268,  0.0206, -0.6454],
        [ 1.3653, -0.3959,  1.2509]], grad_fn=<CloneBackward>)


In [23]:
jacobian.requires_grad

True